### Get champion by name
GET http://localhost:1234/champions/renata

### Get all champions
GET http://localhost:1234/champions

### Get all champions associated with Shurima
GET http://localhost:1234/champions/region/bandle

### Get all champions based on several filters
GET http://localhost:1234/champions?resource=mana&regions=freljord

### Get all champions associated with El Vacio
GET http://localhost:1234/champions/region/Vacío

### Get all champions from a specific position
GET http://localhost:1234/champions/position/central

### Get all champions from a specific position
GET http://localhost:1234/champions/year/2022

### Get all champions from a specific position
GET http://localhost:1234/champions/specie/Ser Del Vacio

### Create a new Champion entry
POST http://localhost:1234/champions
Content-Type: application/json

{
    "name": "Aatrox",
    "encrypted_name": "lleczi",
    "gender": "Masculino",
    "positions": ["Superior"],
    "species": ["Darkin"],
    "resource": "Ninguno",
    "range_type": ["Cuerpo A Cuerpo"],
    "regions": ["Runeterra", "Shurima"],
    "release_year": 2013,
    "icon_url": "https://www.dropbox.com/s/mx655n4pgezeq5k/Aatrox.png?dl=1",
    "encrypted_champ_icon_url": "https://www.dropbox.com/s/epcfr8cf4a0s6jo/lleczi.png?dl=1",
    "encrypted_quote_icon_url": "https://www.dropbox.com/s/i1vf17fznctl8y7/lleczi.png?dl=1",
    "abilities": [
      "Heraldo de la Destrucción",
      "La Espada Darkin",
      "Cadenas Infernales",
      "Impulso Siniestro",
      "Destructor de Mundos"
    ],
    "emojis": [
      ":cloud_lightning:",
      ":man_scientist_tone1:",
      ":robot:",
      ":mechanical_arm:"
    ],
    "quotes": [
      "La guerra saca a relucir nuestro verdadero ser.",
      "Sé lo que se esconde en el corazón de los hombres.",
      "Que el miedo se vuelva furia.",
      "El dolor es temporal, la victoria es eterna.",
      "Tryndamere... Mi mayor creación."
    ],
    "abilities_icons_url": [
      "https://www.dropbox.com/s/0kffg2gbe8frdul/lleczia.png?dl=1",
      "https://www.dropbox.com/s/iw5kp2ttjdnu9ua/lleczib.png?dl=1",
      "https://www.dropbox.com/s/7giyfxqfcnm21hn/lleczic.png?dl=1",
      "https://www.dropbox.com/s/o3eqj9ubiim9z3e/lleczih.png?dl=1",
      "https://www.dropbox.com/s/38a54ximxv6hm45/lleczip.png?dl=1"
    ],
    "aka": "La Espada Darkin."
  }

### Delete a champion
DELETE http://localhost:1234/champions/65d572019d7961d0ca1ef7b5

### Update fields for champion
PATCH http://localhost:1234/champions/65d572019d7961d0ca1ef7b5
Content-Type: application/json

{
  "name": "Aatrox",
  "range_type": ["Cuerpo A Cuerpo"],
  "regions": ["Runeterra", "Shurima"]
}